version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "${MAILPIT_PORT:-8025}:8025"
      - "${SMTP_PORT:-1025}:1025"

volumes:
  postgres_data: