CREATE TABLE users (
    id SERIAL PRIMARY KEY ,
    email VARCHAR(255) NOT NULL UNIQUE ,
    password_hash VARCHAR(255) NOT NULL,
    is_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE refresh_tokens (
    id SERIAL PRIMARY KEY ,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE ,
    token VARCHAR(255) NOT NULL UNIQUE ,
    expires_at TIMESTAMP NOT NULL ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

